In [9]:
# R Command Prompt

myString <- "Hello, World!"
print ( myString)


# R Script File
# writing your programs in script files and then you execute those scripts at your command prompt with the help of R interpreter called Rscript
# format  -  $ Rscript test.R 

[1] "Hello, World!"


### R - Data types

Variables are nothing but reserved memory locations to store values. This means that, when you create a variable you reserve some space in memory.

The variables are assigned with R-Objects and the data type of the R-object becomes the data type of the variable. There are many types of R-objects. The frequently used ones are −

Vectors

Lists

Matrices

Arrays

Factors

Data Frames

The simplest of these objects is the vector object and there are six data types of these atomic vectors, also termed as six classes of vectors. The other R-Objects are built upon the atomic vectors.

In [13]:
# There are 6 classes of vectors

# 1. Logical
#-----------
# examples :   TRUE, FALSE

x = TRUE
print(class(x))
print(typeof(x))

[1] "logical"
[1] "logical"


In [14]:
# 2. Numeric
#-----------
# examples :   2.5, 3

x = 2.5
z = 3


print(class(x))
print(typeof(x))

print(class(z))
print(typeof(z))

[1] "numeric"
[1] "double"
[1] "complex"
[1] "complex"
[1] "numeric"
[1] "double"


In [15]:
# 3. Integer
#-----------
# examples :   1L

x = 1L

print(class(x))
print(typeof(x))

[1] "integer"
[1] "integer"


In [17]:
x = 1L
x

[1] 1

In [18]:
# 4. Complex
#-----------
# examples :   1L

y = 1 + 2i
print(class(y))
print(typeof(y))

[1] "complex"
[1] "complex"


In [21]:
# 5. Character
#-----------
# examples :   'a' , '"good", "TRUE", '23.4'

x= 'a'
y = "good"
z = "TRUE"
p = '23.4'

print(class(z))
print(typeof(z))

[1] "character"
[1] "character"


In [25]:
# 6. Raw
#-----------
# examples :   "Hello" is stored as 48 65 6c 6c 6f

x = charToRaw('Hello')

print(class(x))
print(typeof(x))
print(x)

[1] "raw"
[1] "raw"
[1] 48 65 6c 6c 6f


Vectors

When you want to create vector with more than one element, you should use c() function which means to combine the elements into a vector.

In [26]:
# Create a vector.
apple = c('red','green',"yellow")
print(apple)

# Get the class of the vector.
print(class(apple))

[1] "red"    "green"  "yellow"
[1] "character"


List

A list is an R-object which can contain many different types of elements inside it like vectors, functions and even another list inside it.

In [27]:
list1 = list(c(2,5,3),21.3,sin)

# Print the list.
print(list1)

[[1]]
[1] 2 5 3

[[2]]
[1] 21.3

[[3]]
function (x)  .Primitive("sin")



In [28]:
print(class(list1))

[1] "list"


Matrices

A matrix is a two-dimensional rectangular data set. It can be created using a vector input to the matrix function.

In [29]:
mat1 = matrix(c(1,2,3,4,5,6), nrow = 3, ncol = 2, byrow = TRUE)

In [30]:
print(mat1)

     [,1] [,2]
[1,]    1    2
[2,]    3    4
[3,]    5    6


In [31]:
print(class(mat1))

[1] "matrix"


Arrays

While matrices are confined to two dimensions, arrays can be of any number of dimensions. The array function takes a dim attribute which creates the required number of dimension.

In [33]:
a = array(c('a', 'b'), dim = c(3,3,2))

In [34]:
print(a)

, , 1

     [,1] [,2] [,3]
[1,] "a"  "b"  "a" 
[2,] "b"  "a"  "b" 
[3,] "a"  "b"  "a" 

, , 2

     [,1] [,2] [,3]
[1,] "b"  "a"  "b" 
[2,] "a"  "b"  "a" 
[3,] "b"  "a"  "b" 



In [35]:
print(class(a))

[1] "array"


Factors

Factors are the r-objects which are created using a vector. It stores the vector along with the distinct values of the elements in the vector as labels. The labels are always character irrespective of whether it is numeric or character or Boolean etc. in the input vector. They are useful in statistical modeling.

Factors are created using the factor() function. The nlevels functions gives the count of levels.

In [37]:
v = c('a', 'b', 'c', 'a', 'a', 'b', 'a')
f = factor(v)

In [38]:
print(v)

[1] "a" "b" "c" "a" "a" "b" "a"


In [39]:
print(f)

[1] a b c a a b a
Levels: a b c


In [40]:
print(nlevels(f))

[1] 3


In [41]:
print(class(f))

[1] "factor"


Data Frames

Data frames are tabular data objects. Unlike a matrix in data frame each column can contain different modes of data. The first column can be numeric while the second column can be character and third column can be logical. It is a list of vectors of equal length.

Data Frames are created using the data.frame() function.

In [42]:
df = data.frame(
   gender = c("Male", "Male","Female"), 
   height = c(152, 171.5, 165), 
   weight = c(81,93, 78),
   Age = c(42,38,26)
)

In [43]:
print(df)

  gender height weight Age
1   Male  152.0     81  42
2   Male  171.5     93  38
3 Female  165.0     78  26


In [44]:
print(class(df))

[1] "data.frame"
